from vgamepad import XUSB_BUTTON

A   = XUSB_BUTTON.XUSB_GAMEPAD_A
B   = XUSB_BUTTON.XUSB_GAMEPAD_B
X   = XUSB_BUTTON.XUSB_GAMEPAD_X
Y   = XUSB_BUTTON.XUSB_GAMEPAD_Y

DPAD_DOWN   = XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN
DPAD_UP     = XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP
DPAD_LEFT   = XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT
DPAD_RIGHT  = XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT

LEFT_TRIGGER    = 0x1100
RIGHT_TRIGGER   = 0x1200
LEFT_SHOULDER   = XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER
RIGHT_SHOULDER  = XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER
LEFT_THUMB      = XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB
RIGHT_THUMB     = XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB


